sudo: false
dist: trusty
language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
    env:
    - TEST_COVERAGE=true

install:
- if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer install --no-interaction; fi
- if [[ $TEST_COVERAGE == 'true' ]]; then composer show; fi

script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage; fi
- if [[ $TEST_COVERAGE == 'true' ]]; then composer cs-check; fi

after_script:
- if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage; fi